### ISSUE TITLE
Running it on port other than 80

### ISSUE THREAD

**Issue by ShadabFaiz** [nsg/immich-distribution#117]
### Question

I have nextcloud install on my manjaro OS. It also runs on port 80. Is it possible to run it on any other port ?

**Comment by nsg** [comment]
I have a working solution in #118, I will add a few tests and then hopefully merge later today.

With this change you will be able to configure the port like below, the full documentation will appear [here](https://immich-distribution.nsg.cc/configuration/haproxy/) when it's merged.

```
sudo snap set immich-distribution haproxy-http-bind="*:8880"
```

I will close this issue when it's released to the stable channel.

Thank you for an excellent suggestion!

**Comment by nsg** [comment]
Released to stable.
