### ISSUE TITLE
nothing is running 

### ISSUE THREAD

**Issue by unimatrix-zeroo** [nsg/immich-distribution#129]
### Question

please help
 are there some logs? 
how can i check if a service is not running?
 i am new too linux and all my photos on immich. 
i refrehed the sanp vom 1.81.1 to 1.85.1
sorry for my bad english

**Comment by unimatrix-zeroo** [comment]
i fond this in journalctl --lines 100 -p err..crit :   Failed to start Service for snap application immich-distribution.haproxy.

**Comment by unimatrix-zeroo** [comment]
after 2 hours do nothing http ist running, but i can t enable https
can you help me please

**Comment by nsg** [comment]
Port `3001` is the backend server instance. I guess the error message you got was from your browser?

Can you access `/haproxy` via a browser, like `http://immich.example.com/haproxy` or `http://192.168.1.100/haproxy`? Do you see any red services there?

List all logs with `journalctl -n 100 -u snap.immich-distribution.*` or look at a specific service like the server instance with `journalctl -en 100 -u snap.immich-distribution.immich-server.service`.

Did I understand you correct that you use the built in let's encrypt? Can you see if you have haproxy-https-bind configured like this:

```
snap get immich-distribution haproxy-https-bind
*:443
```

Also, make sure that `snapctl get https-enabled` still is enabled.

**Comment by unimatrix-zeroo** [comment]
yes i use buildin acme
can access haproxy via http
all services are green.
login via http works for all users only https not working
disable and enable https not working
i tried : sudo snap set immich-distribution https-enabled="false" and sudo snap set immich-distribution https-enabled="true"
how can i enable  snapctl get https-enabled

**Comment by nsg** [comment]
The `snap set ...` commands is stored inside snapd:s database.

`https-enabled` set to `true` should enable the https frontend in haproxy. Do you see it from `/haproxy`?

> if i install a new server, backup the old and restore all on the new one. maybe that works? or is the https config saved in the database?

Maybe, hard to guess without knowing what the problem is.

I think this is a easy problem to fix, I just need to understand whats need to be done. I will try to replicate the problem on my system.

**Comment by nsg** [comment]
I may have found a culprit, I bumped HAProxy to a newer version a few releases ago I _think_ this may fix it. I have been able to replicate your problem (or something simulerar) so I will investigate deeper it this do not fix it.

**Comment by unimatrix-zeroo** [comment]
yes in /haproxy i see https and it´s green, but the port isn´t open

![image](https://github.com/nsg/immich-distribution/assets/69356938/229bebde-9f56-4b77-95b2-6e72ded27551)

**Comment by nsg** [comment]
Thank you for the bug report, I have released a fix and I think it will work for you know.

**Comment by unimatrix-zeroo** [comment]
THX 

all up and running

**Comment by unimatrix-zeroo** [comment]
THX

all up and running

you are the best  :)
