### ISSUE TITLE
How to add an external library on a NAS

### ISSUE THREAD

**Issue by LesKent** [nsg/immich-distribution#161]
### Question

I have the Immich snap working great and thanks for making it so easy. Dusting off my 40+ year old BSD skills to figure out modern Linux is not always easy... The question I have is how can I add an Immich external library to a NAS server. I got the NAS mount part on the ubuntu OS working fine but I'm unsure where to mount it so that Immich snap version can access it and what the correct path naming is? The documentation and support suggestions I've found so far is all about docker version and some tidbits I've seen suggest snap solutions appear to have limitations on paths that can be accessed. 
Thanks

**Comment by nsg** [comment]
I'm glad that you finds it useful.

I have not yet documented external libraries at the [documentation webpage](https://immich-distribution.nsg.cc/configuration/storage/). You may still find i useful. I used systemd mounts in the examples, but any mounts will of course work.

In short, any place under `/var/snap/immich-distribution/common` will work. So the easiest way it so mount the NAS in a folder under that path, or create a bind mount from your preferred location.

**Comment by nsg** [comment]
I did a little refactor of the documentation, here is a [new link](https://immich-distribution.nsg.cc/configuration/library/external/).
