### ISSUE TITLE
Server in dev mode

### ISSUE THREAD

**Issue by Cflsft** [nsg/immich-distribution#191]
### Question

How can I run immich in dev mode?

**Comment by nsg** [comment]
Like [developer mode](https://snapcraft.io/docs/install-modes)? I guess it should work, but why? Or are you asking [how to build](https://snapcraft.io/docs/snapcraft-overview) the snap yourself? Can you specify what you are asking?

**Comment by Cflsft** [comment]
I want "play" with the immich api and from the immich documentation: "The generated SDK is based on the immich-openapi-specs.json file, which is autogenerated by the server when running in development mode.". I have installed your immich snap (by the way it's great), and want to know how run the immich server in developer mode.

**Comment by nsg** [comment]
Ah, the API is available at `/api/` and the API docs are available here https://immich.app/docs/api

You need to generate a API Key under your user and pass it in as the HTTP header `X-API-KEY`.

For example in python I do this:

```python
headers = { "X-API-KEY": secret, "Accept": "application/json" }
r = requests.get("http://127.0.0.1/api/people", headers=headers)
print(r.json())
```

Building the `openapi-specs.json` is only relevant if you have modified the Immich sources and changed the server api:s.

**Comment by Cflsft** [comment]
I needed the openapi-specs.json file to generate code for .NET, but I have discovered that it doesn't work in MAUI due to a bug. Thank you for your help.

**Comment by nsg** [comment]
Ah, I understand. My understanding is that the Immich developers commits the latest file whenever needed so you can [browse to the file from the upstream sources](https://github.com/immich-app/immich/blob/main/open-api/immich-openapi-specs.json). I hope you find a way around the bug.
