### ISSUE TITLE
how to run immich-admin utility in snap version?

### ISSUE THREAD

**Issue by noexept** [nsg/immich-distribution#217]
### Question

How can I run immich-admin utility in snap version?

```
# /snap/immich-distribution/154/usr/src/app/bin/immich-admin --help
/snap/immich-distribution/154/usr/src/app/bin/immich-admin: 3: /usr/src/app/start.sh: not found
#
```
Thank you

**Comment by nsg** [comment]
The `immich-admin` script assumes it's inside an OCI (Docker) container. I will try to include it in next release.

Temporary workaround is:

```bash
snap run --shell immich-distribution.debug
source $SNAP/bin/load-env
cd $SNAP/usr/src/app
node dist/main immich-admin
```

**Comment by nsg** [comment]
Added in #219, I will release it together with the 1.115 release.
