### ISSUE TITLE
CUDA Support

### ISSUE THREAD

**Issue by zacksiri** [nsg/immich-distribution#245]
### Question

I have a GPU and NVIDIA driver installed already how do I enable immich to use the GPU?

**Comment by nsg** [comment]
immich-distribution only supports machine learning on the CPU. I have made this choice due limited time and resources on my part, and I have also found CPU to be fast enough for most users. So, I'm sorry, you can't enable CUDA support in immich-distribution, if this is important for you I suggest the upsteam [docker-compose based installation](https://immich.app/docs/install/docker-compose).

**Comment by zacksiri** [comment]
@nsg thank you for your reply. I submitted a PR https://github.com/nsg/immich-distribution/pull/246 not sure if this will suffice.
